"use client";

import { useState } from "react";
import { useQueryClient } from "@tanstack/react-query";
import { toast } from "sonner";
import {
  CheckCircle2,
  Lightbulb,
  Loader2,
  RefreshCw,
  Sparkles,
  Gavel,
} from "lucide-react";
import { Button } from "@/components/ui/button";
import type { Summary } from "@/lib/fireflies/types";

export function SummaryPanel({
  meetingId,
  summary,
  hasTranscript,
}: {
  meetingId: string;
  summary: Summary | null;
  hasTranscript: boolean;
}) {
  const qc = useQueryClient();
  const [regenerating, setRegenerating] = useState(false);

  async function regenerate() {
    setRegenerating(true);
    try {
      const res = await fetch(
        `/api/meetings/${meetingId}/summary`,
        { method: "POST" },
      );
      if (!res.ok) {
        const err = await res.json().catch(() => ({}));
        throw new Error(err.error || "Failed to regenerate summary");
      }
      const data = await res.json();
      qc.setQueryData(["meeting", meetingId], (old: any) => {
        if (!old) return old;
        return {
          ...old,
          meeting: {
            ...old.meeting,
            summary: {
              id: data.id,
              overview: data.overview,
              keyPoints: data.keyPoints,
              decisions: data.decisions,
            },
          },
        };
      });
      toast.success("Summary regenerated by AI");
    } catch (e: any) {
      toast.error(e?.message || "Could not regenerate summary");
    } finally {
      setRegenerating(false);
    }
  }

  if (!summary) {
    return (
      <div className="flex flex-col items-center justify-center rounded-xl border border-dashed border-border bg-card p-10 text-center">
        <Sparkles className="h-8 w-8 text-primary" />
        <h3 className="mt-3 text-lg font-semibold">No summary yet</h3>
        <p className="mt-1 max-w-sm text-sm text-muted-foreground">
          {hasTranscript
            ? "Generate an AI summary, key points, and decisions from this transcript."
            : "Add a transcript first, then generate an AI summary."}
        </p>
        {hasTranscript && (
          <Button
            onClick={regenerate}
            disabled={regenerating}
            className="mt-4 gap-2 bg-primary text-primary-foreground hover:opacity-90"
          >
            {regenerating ? (
              <Loader2 className="h-4 w-4 animate-spin" />
            ) : (
              <Sparkles className="h-4 w-4" />
            )}
            Generate AI summary
          </Button>
        )}
      </div>
    );
  }

  return (
    <div className="space-y-5">
      <div className="flex items-center justify-between">
        <div className="flex items-center gap-2">
          <Sparkles className="h-5 w-5 text-primary" />
          <h3 className="text-base font-semibold">AI Summary</h3>
        </div>
        <Button
          variant="outline"
          size="sm"
          onClick={regenerate}
          disabled={regenerating || !hasTranscript}
          className="gap-1.5"
        >
          {regenerating ? (
            <Loader2 className="h-3.5 w-3.5 animate-spin" />
          ) : (
            <RefreshCw className="h-3.5 w-3.5" />
          )}
          Regenerate
        </Button>
      </div>

      {/* Overview */}
      <div className="rounded-xl border border-border bg-card p-4">
        <p className="text-[11px] font-semibold uppercase tracking-wide text-muted-foreground">
          Overview
        </p>
        <p className="mt-2 text-sm leading-relaxed text-foreground/90 whitespace-pre-line">
          {summary.overview}
        </p>
      </div>

      {/* Key points */}
      {summary.keyPoints.length > 0 && (
        <div className="rounded-xl border border-border bg-card p-4">
          <div className="flex items-center gap-2">
            <Lightbulb className="h-4 w-4 text-primary" />
            <p className="text-[11px] font-semibold uppercase tracking-wide text-muted-foreground">
              Key Points
            </p>
          </div>
          <ul className="mt-3 space-y-2">
            {summary.keyPoints.map((k, i) => (
              <li
                key={i}
                className="flex items-start gap-2 text-sm leading-relaxed"
              >
                <span className="mt-1 flex h-1.5 w-1.5 shrink-0 rounded-full bg-primary" />
                <span>{k}</span>
              </li>
            ))}
          </ul>
        </div>
      )}

      {/* Decisions */}
      {summary.decisions.length > 0 && (
        <div className="rounded-xl border border-border bg-card p-4">
          <div className="flex items-center gap-2">
            <Gavel className="h-4 w-4 text-primary" />
            <p className="text-[11px] font-semibold uppercase tracking-wide text-muted-foreground">
              Decisions
            </p>
          </div>
          <ul className="mt-3 space-y-2">
            {summary.decisions.map((d, i) => (
              <li
                key={i}
                className="flex items-start gap-2 text-sm leading-relaxed"
              >
                <CheckCircle2 className="mt-0.5 h-3.5 w-3.5 shrink-0 text-primary" />
                <span>{d}</span>
              </li>
            ))}
          </ul>
        </div>
      )}
    </div>
  );
}
